xinnan-tech/xiaozhi-esp32-server

- main/xiaozhi-server/core/utils/util.py
修复启动时SyntaxWarning: invalid escape sequence '\]'
half_width_punctuations = '!"#$%&\'()*+,-./:;<=>?@[\]^_`{|}~'的报错问题
> 修复V0.1.2版本启动报错问题

- main/xiaozhi-server/core/handle/intentHandler.py
修复指令text包含标点的情况下，无法正确识别退出指令的问题
> fix: 退出指令无法识别

- main/xiaozhi-server/core/providers/llm/coze/coze.py
历史消息在coze 上可配置历史消息的轮次。
同个会话id，coze 上自动带历史上下文。
会话和当前session关联。一次连接一个会话，断开后，重连是新会话无历史消息。
> 添加 使用 coze 会话, 使用coze自带的历史消息。

- main/xiaozhi-server/core/handle/receiveAudioHandle.py
#289 
原理说明：
esp32是每帧音频上报后端，刚说话时首字和其他内容很大概率不在同一帧，首字所在的音频帧可能不够触发vad检测阈值，此前的做法是把vad检测不通过的帧全部丢掉，就可能把首字丢了
修改后保留了最新的5个音频帧而不是全部丢弃，VAD检测通过后，ASR合成时把这5帧加在前面，就可以解决丢字问题
> fix: ASR句首丢字问题

- main/xiaozhi-server/core/providers/llm/dify/dify.py
修复DifyLLM不支持多轮对话的问题。如果有conversation_id则将conversation_id传递给dify接口用于定位同一对话
> feat: 支持dify的多轮对话, chat工作流支持持久化conversation_id #296

- main/xiaozhi-server/core/providers/tts/base.py
在tts.base的`AudioSegment.from_file`处额外传递 `-nostdin` 参数，防止 FFmpeg 在`Windows `环境下等待标准输入，导致阻塞执行。
> fix(tts.base): 修复 AudioSegment.from_file 读取音频时阻塞的问题

- main/xiaozhi-server/core/connection.py
解决客户端websocket连接断开后异步消费线程不销毁的BUG
> fix:解决客户端websocket连接断开后异步消费线程不销毁的BUG

- main/xiaozhi-server/config.yaml
- main/xiaozhi-server/core/connection.py
- main/xiaozhi-server/core/handle/intentHandler.py
- main/xiaozhi-server/core/providers/intent/base.py
- main/xiaozhi-server/core/providers/intent/intent_llm/intent_llm.py
- main/xiaozhi-server/core/providers/llm/xinference/xinference.py
- main/xiaozhi-server/plugins_func/functions/get_news.py
- main/xiaozhi-server/plugins_func/functions/get_weather.py
1，为意图识别intent_llm单独配置独立的LLM，可在.config.yaml中的IntentLLM根据需求自行配置，我的代码中是使用的本地部署的xinference。
2，为意图识别intent_llm增加了天气和新闻查询功能，主要修改了intent_llm.py，base.py，connection.py，intentHandler.py几个文件中相关的代码
3，根据个人需要，添加了xinference作为LLM
> 意图识别intent_llm单独配置独立的LLM，意图识别intent_llm增加天气和新闻查询function

- main/xiaozhi-server/plugins_func/functions/handle_device.py
> fix:修复handle_device.py 参数类型定义错误导致DoubaoLLM调用报 400 错误

- main/xiaozhi-server/plugins_func/functions/handle_device.py
- main/xiaozhi-server/plugins_func/functions/hass_set_state.py
上个pr #562 遗漏了hass_set_state.py，并且number 类型改为integer 更加准确一点
> 修复function call的参数类型定义错误

- main/xiaozhi-server/core/utils/util.py
freeipapi.com接口在部分地区无法访问获取bug修改
将失效的https://freeipapi.com/api/json替换为https://whois.pconline.com.cn/ipJson.jsp?json=true
#513
> get_ip_info接口优化

- main/xiaozhi-server/requirements.txt
requests 经过socks代理访问网络的时候需要依赖第三方package，对应PySocks包。否则会出现"Missing dependencies for SOCKSsupport."错误。
https://requests.readthedocs.io/en/latest/user/advanced/#socks
> 为xiaozhi-server的requirments.txt文件添加PySocks包

- main/manager-api/src/main/java/xiaozhi/modules/device/dto/DeviceReportRespDTO.java
- main/manager-api/src/main/java/xiaozhi/modules/device/service/impl/DeviceServiceImpl.java
xiaozhi-esp32的最新更新已经支持从OTA获取websocket地址，不需要再次编译固件。
见这个提交：https://github.com/78/xiaozhi-esp32/commit/3404180a776b5473531fbb9658add706155e32a8
本PR已经自测通过。
使用test_page.html也测试通过：
```
[23:37:52.874] 正在检查OTA状态...
[23:37:52.978] OTA检查结果: {"server_time":{"timestamp":1745249872874,"timeZone":"Asia/Shanghai","timezone_offset":480},"firmware":{"version":"1.0.0","url":"http://localhost:8002/xiaozhi/ota/download"},"websocket":{"url":"wss://{我的私有地址}/xiaozhi/v1/"}}
[23:37:52.979] OTA检查通过，开始连接WebSocket...
[23:37:52.979] 正在连接: wss://{我的私有地址}/xiaozhi/v1/?device-id=00%3A11%3A22%3A33%3A44%3A55&client-id=web_test_client
```
> feat: 支持通过OTA更新websocket地址

- main/manager-web/.env.production
- main/manager-web/package.json
- main/manager-web/vue.config.js
- 添加 `VUE_APP_PUBLIC_PATH` 环境变量，允许用户自行指定智控台（前端）的部署路径并编译
- 依赖补充 `"dotenv"`
> 添加前端部署路径环境变量

- main/xiaozhi-server/core/providers/tts/base.py
tts未及时响应，多次尝试逻辑修复。（tts失败会生成空文件，需删除空文件，达成While的条件，再次调用tts）
> fix：修复tts多次尝试逻辑

- main/xiaozhi-server/config/config_loader.py
- main/xiaozhi-server/config/settings.py
定义：
- `config.yaml`为默认配置； 定义当前支持的各种可设置的参数和默认参数；
- `data/.config.yaml` 为自定义配置；用户设置相关参数，未设置部分读取 `config.yaml`默认配置
参考“**约定大于配置**”的思想，使用者通过设置自定义配置即可完成启动，无需关默认配置项，减少用户冗余配置；
例如：仅通过以下 `data/.config.yaml` 配置，即可完成使用AliLLM，无需编写其他无用配置
```yaml
selected_module:
LLM: AliLLM
Intent:
intent_llm:
type: intent_llm
llm: AliLLM
LLM:
AliLLM:
api_key: sk-********************************
```
> 采用约定大于配置的原则，减少用户冗余设置，用户仅调整自定义设置

- main/xiaozhi-server/core/providers/tts/doubao.py
> fix: doubao tts token

- main/xiaozhi-server/core/mcp/MCPClient.py
- main/xiaozhi-server/core/mcp/manager.py
- main/xiaozhi-server/mcp_server_settings.json
- main/xiaozhi-server/requirements.txt
当前MCP client的实现只支持`stdio`的模式，有些时候本地环境不方便，需要使用`sse`等模式时直接报错。
这里增强了一下这块的能力，已经自测通过可以使用。
同时在示例的`mcp_server_settings.json`中添加了一个描述。
使用示例：
```json
"example-sse-server": {
"url": "http://your-server-ip:your-port/sse"
}
```
> feat: MCP server支持使用sse模式

- Dockerfile-server
- main/xiaozhi-server/core/handle/functionHandler.py
- main/xiaozhi-server/core/handle/intentHandler.py
- main/xiaozhi-server/core/providers/intent/intent_llm/intent_llm.py
- main/xiaozhi-server/plugins_func/functions/get_news_from_different_source.py
获取新闻标题，用户想要深入了解的话，会查看新闻全文并总结。
- 使用 https://github.com/ourongxing/newsnow （https://newsnow.busiyi.world/c/focus） 获取新闻，可以自行部署
- 使用 https://github.com/microsoft/markitdown 处理网页。
> feat: 添加多个新闻源，并修复大模型意图识别没有处理ActionResponse的问题

- main/xiaozhi-server/config.yaml
- main/xiaozhi-server/core/handle/receiveAudioHandle.py
新增：
新增在python服务端在config配置内自定义结束词提示词（end_prompt），仅在enable为True时触发结束聊天，否则自动默认清理资源退出。
----
配置enable属性是为了让用户更灵活控制结束词，即使暂时不想使用结束词也不需要删除该配置。
close(#963)
> feature: 新增结束词prompt自定义能力。

- main/xiaozhi-server/core/providers/llm/ollama/ollama.py
为本地ollama部署qwen3大语言模型添加适配！在识别到启用为qwen3大模型的时候自动添加no_think停用推理模式，并过滤<think></think>标签转入给TTS（因为qwen3虽然用no_think停用推理后还是会输出<think></think>转入到TTS）
> Update ollama.py 为本地ollama部署qwen3大语言模型添加适配！

- main/xiaozhi-server/test/test_page.html
1、修复“第一段话有语音输出，后续的回答都是静音”问题
2、发送消息时重置音频状态，避免“连续对话时，前一次交互的音频数据残留在 audioBufferQueue 中，导致新旧数据混合，播放逻辑混乱。”问题
3、添加“断开连接后，所有音频相关的状态都被重置”
> fix：修复“小智服务器测试页面播放语音问题”

- main/xiaozhi-server/core/mcp/MCPClient.py
当前SSEClient不支持access_key参数和认证，无法通过SSE直接连接homeassistant的mcp_server。添加了认证的header，经过测试可以正常连接homeassistant。
测试的mcp配置文件：
"mcpServers": {
"Home Assistant": {
"url": "http://192.168.31.22:8123/mcp_server/sse",
"API_ACCESS_TOKEN":    "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiIxZTFiYjYwNGM4ZDY0YmRlODU3NWFmZmFhNDVlZDEzMSIsImlhdCI6MTc0ODE3NDI3NiwiZXhwIjoyMDYzNTM0Mjc2fQ.E5QjiAQE_utNexB1D2_Hbd7mptviP7GPjfGkeA3Zdq8"
}
}
> SSEClient支持认证

- main/xiaozhi-server/core/connection.py
原代码
```
if tools_call is not None:
tool_call_flag = True
if tools_call[0].id is not None:             # tools_call[0] 会触发 IndexError
```
> fix: 使用deepseek r1-0528模型时，tools_call为空list，tools_call[0]报错

- main/manager-api/src/main/resources/lua/emptyAll.lua
-- emptyAll.lua
1、当redis被多个项目使用时，清空了其它项目的库（影响其它项目的运行）
> 🐞 fix: 只清空当前数据库，不清空整个数据库

- main/xiaozhi-server/core/connection.py
根据xiaozhi websocket协议，hello消息由客户端发送，服务器端回复。当前实现中当客户端连接成功时会立即发送hello，不符合协议设计。
> 客户端连接成功时不主动发送hello

- Dockerfile-server
pip install mcp-proxy会安装到/usr/local/bin/mcp-proxy，从编译镜像移动到生产镜像内
> fix: 修复mcp-proxy命令不存在

- main/manager-api/src/main/java/xiaozhi/modules/agent/service/impl/AgentMcpAccessPointServiceImpl.java
- main/manager-api/src/main/java/xiaozhi/modules/sys/utils/WebSocketClientManager.java
--WebSocketClientManager.java
1.构建websocket对象的时候，添加可以设置缓冲区大小
2.断开连接的日志添加断开原因的内容
--AgentMcpAccessPointServiceImpl.java
1.设置每个websocket的缓冲区为1m，bug原因：缓存区太小，数据量太大，导致直接断开连接
> 修复mcp工具太多会获取不到内容的bug

- main/xiaozhi-server/core/connection.py
> 使用的大模型为 Qwen3-235B-A22B-Instruct-2507-AWQ
> fix: 修复qwen模型返回toolcall的arguments为None时导致后续请求400

- main/manager-api/pom.xml
--pom.xml
1.升级了springdoc 2.8.8, knife4j4.6 与 doc2.7.7版本存在兼容问题,按照官方建议升级到2.8.8 解决了此bug 2.升级了 commons-lang3 3.18.0,springdoc 2.8.8 依赖commons-lang低版本存在CVE-2025-48924漏洞,升级版本解决
> 修复api接口文档页面,接口文档和点击按钮的说明不一致,串标题的bug

- main/xiaozhi-server/core/providers/tts/huoshan_double_stream.py
在使用```火山双流式语音合成```时发现在添加使用additions参数时，不生效，查阅官网文档后发现，是因为additions参数是配置在req_params下级参数中，原代码req_params和additions平级了，文档地址:https://www.volcengine.com/docs/6561/1329505
> 修复-火山双流式语音合成-additions参数配置
