- core/connection.py
- core/handle/audioHandle.py
修复了语音合成会漏掉第一句的问题
主要是调整了tts.start-tts.sentence_start-tts.sentence_end-tts.stop的时序处理
> fix audiohandler:修复了语音合成会漏掉第一句的问题

- .gitignore
- README.md
> 📃 docs(readme): 增加开发测试部署方式

- config.yaml
- core/connection.py
- core/providers/llm/ollama/ollama.py
> 增加本地大模型ollama支持

- config.yaml
- core/auth.py
- core/connection.py
- docker-compose.yml
> feat: 添加WS TOKEN 认证功能

- Dockerfile
- ZhiKongTaiWeb/package.json
- ZhiKongTaiWeb/yarn.lock
> 🎈 perf: 优化开发体验

- config.yaml
- core/providers/llm/openai/openai.py
跳过使用Open ai 接口时，DeepSeek-R1 模型的深度思考内容
> 跳过使用Open ai 接口时，DeepSeek-R1 模型的深度思考内容

- Dockerfile
- Dockerfile-pip
- ZhiKongTaiWeb/README.md
- ZhiKongTaiWeb/package.json
- docker-compose.yml
- docs/Deployment.md
- manager/http_server.py
dockerfile移除网络下载
添加前端说明文档
修改静态文件调用
> 🎈 perf: 优化开发

- core/utils/util.py
> 更新util.py的def remove_punctuation_and_length函数解决返回元组报错

- config.yaml
- core/providers/tts/tts_302ai.py
添加对302.AI TTS服务的支持，并具有以下功能：
- 更新配置以支持302.AI语音模型
- 支持国际和中国大陆API端点
- 实施具有适当身份验证的简化请求格式
- 添加具有可自定义选项的默认语音配置”
> feat: add 302.ai TTS integration

- config.yaml
- core/providers/llm/coze/coze.py
- requirements.txt
> 修改了coze的实现方式,使用了v3接口,修复了只能对话一次的bug

- main/xiaozhi-server/core/connection.py
- main/xiaozhi-server/core/handle/intentHandler.py
修复ActionResponse为NOTFOUND时候卡住主线程的bug
> 修复ActionResponse为NOTFOUND时候卡住主线程的bug

- main/xiaozhi-server/config.yaml
- main/xiaozhi-server/core/connection.py
- main/xiaozhi-server/core/handle/musicHandler.py
- main/xiaozhi-server/core/providers/tts/base.py
- main/xiaozhi-server/core/providers/tts/custom.py
- 修复了tts转码的一个兼容问题，32-bit的wav到esp32上会变成噪音
- 增加了自定义tts接口服务，支持自定义参数和header，只要接口是get请求，返回wav格式音频就可以支持
- 本地部署tts 感兴趣可以看下 https://github.com/journey-ad/CosyVoice2-Ex 对显卡要求略高
- 另外考虑到本地部署tts或网络环境差的情况，把tts超时时间作为配置项
> TTS功能的一些修改

- main/xiaozhi-server/config.yaml
- main/xiaozhi-server/core/providers/tts/gpt_sovits_v3.py
fix：GPT_SOVITS_V3-20250228 API
修复：GPT_SOVITS_V3-20250228 API
> fix：GPT_SOVITS_V3-20250228 API

- main/xiaozhi-server/core/handle/iotHandle.py
> 修复iot功能中表达式问题

- main/xiaozhi-server/config.yaml
- main/xiaozhi-server/config/settings.py
- main/xiaozhi-server/docker-compose.yml
#164 自定义asr、tts缓存目录,项目启动自动创建目录
自动创建ASR和TTS的相关缓存目录
> Custom paths asr tts

- README.md
- main/xiaozhi-server/config.yaml
- main/xiaozhi-server/core/providers/asr/volcengine.py
- ASR：采用火山引擎语音识别大模型
- TTS：采用火山引擎语音合成，支持小模型和大模型的语音
> add:支持Gizwits API渠道接口

- main/xiaozhi-server/config.yaml
- main/xiaozhi-server/core/providers/llm/gemini/gemini.py
在代理模式下手动组成request，无论 Steam 是否为 True，返回的均是非steam 格式。
不设置代理时自动切换为google的官方api，走 stream模式。
全局代理容易让系统中其他模块也使用代理，造成无法访问的问题。
测试最新的 gemini flash 2.0可以使用。
> gemini独立代理模式

- main/manager-web/src/components/HeaderBar.vue
- main/manager-web/src/views/login.vue
- main/manager-web/src/views/register.vue
validateInput 函数：该函数用于验证输入是否为空，若为空则显示错误提示并返回 false，否则返回 true。
> 代码复用：将输入验证逻辑封装成一个独立的函数validateInput ，提高代码的复用性。

- main/xiaozhi-server/config.yaml
- main/xiaozhi-server/plugins_func/functions/get_news.py
> feat: 新闻插件开发, 使用function_call支持播放当天新闻 #403

- main/xiaozhi-server/config.yaml
- main/xiaozhi-server/core/providers/llm/AliBL/AliBL.py
实现AliAppLLM基本功能，根据阿里百练API文档：
https://help.aliyun.com/zh/model-studio/user-guide/application-calling/#b660cd08cedxq
#444 
Q：兼容 Dashscope SDK 的认证方式（API Key + App ID验证）
A：√
Q：支持百炼平台特有的参数传递
A：根据我所了解，有些API参数使用会强制要求另一参数传入。计划先实现部分
Q：处理 Dashscope 的响应格式与项目现有结构的兼容性
A：个人觉得，在原有结构上做加法能保证最大兼容
（tips：我不太了解项目代码规范，如有建议欢迎提出）
> add：AliAppLLM

- main/xiaozhi-server/core/handle/sendAudioHandle.py
> 修复音乐播放断开bug

- main/xiaozhi-server/plugins_func/functions/get_weather.py
> feat: 优化查询天气插件

- main/xiaozhi-server/core/providers/tts/aliyun.py
> 增加token过期刷新，修复过期bug

- main/xiaozhi-server/core/connection.py
- main/xiaozhi-server/core/handle/helloHandle.py
- main/xiaozhi-server/core/handle/intentHandler.py
- main/xiaozhi-server/core/handle/receiveAudioHandle.py
- main/xiaozhi-server/core/handle/sendAudioHandle.py
- main/xiaozhi-server/plugins_func/functions/handle_device.py
包含一组功能、性能优化和 bug 修复的提交，具体改动可以看每个 commit 内容
> 一些功能优化和bug修复

- main/xiaozhi-server/config.yaml
- main/xiaozhi-server/core/providers/tts/tencent.py
> feat:增加腾讯云TTS服务

- main/xiaozhi-server/core/connection.py
> fix：普通聊天调试

- main/xiaozhi-server/config.yaml
> feat:新增腾讯云ASR语音识别服务

- .gitignore
- main/manager-api/README.md
- main/manager-api/src/main/java/xiaozhi/modules/sys/controller/AdminController.java
- main/manager-api/src/main/resources/logback-spring.xml
- main/manager-web/README.md
- main/manager-web/src/apis/module/agent.js
- main/manager-web/src/apis/module/user.js
- main/manager-web/src/views/home.vue
- main/xiaozhi-server/config.yaml
- main/xiaozhi-server/core/providers/asr/tencent.py
- main/xiaozhi-server/plugins_func/functions/hass_init.py
#368 重新划分agent-api,修复登录后home页面报错。
> 重新划分agent-api

- main/xiaozhi-server/core/connection.py
- main/xiaozhi-server/core/providers/tts/base.py
> fix：删除多余方法

- main/manager-web/src/components/ViewPasswordDialog.vue
- main/manager-web/src/views/UserManagement.vue
> Web admin modify

- main/xiaozhi-server/test/abbreviated_version/app.js
- main/xiaozhi-server/test/abbreviated_version/test.html
- main/xiaozhi-server/test/opus_test/app.js
- main/xiaozhi-server/test/opus_test/test.html
- main/xiaozhi-server/test/test_page.html
本次PR主要优化了test_page.html中的音频播放卡顿，解决了以下问题：
1. 修复了Opus解码器初始化问题，确保解码器可用后再处理音频
2. 增强了音频缓冲和播放机制的稳定性
3. 简化了代码结构，移除了未使用的备用函数
4. 优化了函数命名和注释，提高代码可读性
> fix: 🐛 优化test_page.html

- main/xiaozhi-server/plugins_func/functions/hass_get_state.py
- main/xiaozhi-server/plugins_func/functions/hass_set_state.py
修正设备状态返回的方法，把正确的结果吐回给LLM，支持灯光色温和rgb颜色调节和查询
修正音量调整到1但实际会调整到100%的bug
> [function]homeassistant操作能力增强

- main/manager-api/src/main/resources/db/changelog/202504151547.sql
- main/xiaozhi-server/core/providers/tts/siliconflow.py
- main/xiaozhi-server/test/abbreviated_version/app.js
- main/xiaozhi-server/test/test_page.html
1. test_page.html混用onclick以及addEventListener，导致无法正常关闭websocket
2. 同时增加了多行log支持，用于打印json
3. 修正硅基流动的CosyVoice TTS音色配置，‘alex’ to 'FunAudioLLM/CosyVoice2-0.5B:alex'
4. 修正硅基流动的CosyVoice TTS Provider的speed缺省配置
> Bug fix test_page.html, 以及TTS_CosyVoiceSiliconflow

- main/xiaozhi-server/config/config_loader.py
- main/xiaozhi-server/config/manage_api_client.py
建议抽取专门类，针对功能包裹校验之类的交互，对外仅展示方法功能接口
> update: 增加对httpClient的统一管理

- main/xiaozhi-server/core/providers/llm/openai/openai.py
OpenAI 格式 LLM API 流式输出时，最后可能输出 `choices=[]` 的特殊 chunk。现有的代码遇到这种情况会抛出 `list index out of range` 异常。
此 PR 添加了对该特殊 chunk 的处理。如果提供商返回了 Token 消耗情况数据，也会一并归入 log。
fix #734
> 处理 OpenAI 格式响应中 `choices` 为空的 chunk

- main/manager-api/src/main/resources/db/changelog/202504082211.sql
- main/manager-api/src/main/resources/db/changelog/202504112044.sql
- main/xiaozhi-server/config.yaml
- main/xiaozhi-server/core/providers/asr/fun_server.py
新增FunASR服务API调用（服务可根据官方说明自行另外部署）， 增加配置与API调用实现
> [Feature]新增funASR服务调用适配

- docs/Deployment_all.md
- main/xiaozhi-server/config.yaml
- main/xiaozhi-server/core/providers/asr/aliyun.py
- main/xiaozhi-server/core/providers/asr/baidu.py
- main/xiaozhi-server/core/providers/asr/doubao.py
- main/xiaozhi-server/core/providers/asr/fun_local.py
- main/xiaozhi-server/core/providers/asr/fun_server.py
- main/xiaozhi-server/core/providers/asr/sherpa_onnx_local.py
- main/xiaozhi-server/core/providers/asr/tencent.py
- main/xiaozhi-server/core/providers/tts/doubao.py
- main/xiaozhi-server/requirements.txt
> 规范asr部分的代码，添加百度asr支持

- main/xiaozhi-server/app.py
效果
----
- Ctrl‑C/kill退出时不再卡住，资源完全释放，
- Windows 与 Unix 行为一致，改动不影响正常业务逻辑。
> fix(app): 修复app.py内的wait_for_exit()，以此解决Windows环境下手动退出时，进程阻塞卡死的问题。

- main/xiaozhi-server/core/providers/llm/gemini/gemini.py
原先的Gemini不支持function-call和代理模式下的stream对话模式，现在支持了。
> feature: 新增Gemini模型支持function_call功能，支持在代理模式下使用流式stream对话模式。

- main/manager-api/src/main/resources/db/changelog/202505081146.sql
- main/manager-api/src/main/resources/db/changelog/db.changelog-master.yaml
- main/xiaozhi-server/core/providers/asr/doubao.py
修复:智控台豆包ASR缺少热词引发的bug
增加:智控台添加百度ASR供应器
> 修复:智控台豆包ASR缺少热词引发的bug

- main/manager-api/src/main/java/xiaozhi/modules/sys/service/impl/SysUserServiceImpl.java
> 用户管理页面的搜索功能增加模糊搜索

- main/xiaozhi-server/config/config_loader.py
- main/xiaozhi-server/performance_tester.py
1. 在性能测试脚本中添加 ASR 的测试任务。
2. 优化测试脚本的部分格式。
3. 忽略掉“ASR/TTS模块输出目录”时，读取配置文件中"ASR", "TTS"为空的情况。以及“根据selected_module创建模型目录”中类似的问题。
> Add ASR performance

- Dockerfile-web
更新第三阶段运行状态的运行jdk镜像，切换包管理器为apk。
已测试arm64、x86架构稳定运行。
issue(##1247)
> fix: 修复docker镜像不兼容arm64架构。

- main/manager-api/src/main/java/xiaozhi/common/exception/RenExceptionHandler.java
- main/manager-api/src/main/java/xiaozhi/common/utils/DateUtils.java
- main/manager-api/src/main/java/xiaozhi/modules/sys/controller/ServerSideManageController.java
- main/manager-api/src/main/java/xiaozhi/modules/sys/controller/SysParamsController.java
- main/manager-api/src/main/java/xiaozhi/modules/sys/dto/EmitSeverActionDTO.java
- main/manager-api/src/main/java/xiaozhi/modules/sys/dto/ServerActionPayloadDTO.java
- main/manager-api/src/main/java/xiaozhi/modules/sys/dto/ServerActionResponseDTO.java
- main/manager-api/src/main/java/xiaozhi/modules/sys/enums/ServerActionEnum.java
- main/manager-api/src/main/java/xiaozhi/modules/sys/enums/ServerActionResponseEnum.java
- main/manager-api/src/main/java/xiaozhi/modules/sys/utils/WebSocketClientManager.java
- main/manager-web/src/apis/module/admin.js
- main/manager-web/src/components/HeaderBar.vue
- main/manager-web/src/router/index.js
- main/manager-web/src/views/ServerSideManager.vue
- main/xiaozhi-server/core/connection.py
- main/xiaozhi-server/core/handle/textHandle.py
> feat: 新增智控台管理websocket服务器端【配置拉取】和【重启】

- main/manager-api/src/main/java/xiaozhi/modules/sys/controller/ServerSideManageController.java
- main/manager-api/src/main/java/xiaozhi/modules/sys/dto/EmitSeverActionDTO.java
- main/manager-api/src/main/java/xiaozhi/modules/sys/dto/ServerActionPayloadDTO.java
- main/manager-api/src/main/java/xiaozhi/modules/sys/enums/ServerActionEnum.java
- main/manager-api/src/main/java/xiaozhi/modules/sys/enums/ServerActionResponseEnum.java
主要修改点：
1. 修改获取服务端列表的方法逻辑，增加判空和潜在空指针的判断。
2. 补充部分注释；
3. 删除无关的个人署名注释；
> chore: 服务端管理接口代码健壮性调整，补充注释与删除署名注释。

- main/xiaozhi-server/test/test_page.html
- 在OTA和WebSocket服务器地址输入框中添加更详细的占位符提示
- 增加本地存储功能，保存并恢复OTA和WebSocket服务器地址
> refactor(test_page.html): 优化UI布局和输入提示，增加本地存储功能

- main/manager-web/src/views/login.vue
- main/manager-web/src/views/register.vue
- main/manager-web/src/views/retrievePassword.vue
> feat: 登录注册等页面密码输入框添加可见属性

- main/manager-api/src/main/resources/db/changelog/202507101201.sql
- main/manager-api/src/main/resources/db/changelog/db.changelog-master.yaml
- main/xiaozhi-server/core/providers/asr/gpt.py
> OpenAI asr

- main/xiaozhi-server/test/js/StreamingContext.js
- main/xiaozhi-server/test/test_page.html
将原本内联在test_page.html中的流式音频处理逻辑重构为独立的StreamingContext类，提高代码可维护性和复用性
> refactor(audio): 将流式音频处理逻辑提取为独立类

- main/manager-api/src/main/resources/db/changelog/202509161701.sql
- main/manager-api/src/main/resources/db/changelog/db.changelog-master.yaml
- main/xiaozhi-server/config.yaml
- main/xiaozhi-server/core/handle/sendAudioHandle.py
- main/xiaozhi-server/core/providers/tts/alibl_stream.py
- main/xiaozhi-server/core/providers/tts/aliyun_stream.py
- main/xiaozhi-server/core/providers/tts/base.py
- main/xiaozhi-server/core/providers/tts/huoshan_double_stream.py
> update: 阿里百炼流式TTS 减少调试日志显示
